# Generated by Django 4.1 on 2023-03-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0003_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('P', 'Para adoção'), ('A', 'Adotado')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
